grids:
    swissgrid:
        resolutions: [1000, 500, 250, 100, 50, 20, 10, 5, 2, 1, 0.5, 0.2, 0.1]
        bbox: [420000, 30000, 900000, 350000]
        tile_size: 256
        srs: epsg:21781

caches:
    local:
        type: filesystem
        http_url: http://taurus/tiles
        folder: /var/www/tiles
    s3:
        type: s3
        http_url: https://%(host)s/%(bucket)s/%(folder)s
        host: s3-eu-west-1.amazonaws.com
        bucket: tiles
        folder: tiles

layer_default:
    grid: swissgrid
    type: wms
    url: http://dev.regiogis-beo.ch/main/wsgi/mapserv_proxy # ${mapserv_url}
    extension: png
    mime_type: image/png
    wmts:
        style: default
    dimensions:
        -   name: VERSION
            default: 1
            value: 1
            values: [1]
    meta: on
    meta_size: 8
    meta_buffer: 128
    connection: user=www-data password=www-data dbname=<db> host=localhost
    sql: ST_Union(ST_Buffer(geom, 10, 2)) FROM <table>
    empty_tile_detection:
        size: 1096
        hash: -2225832598072171888
    empty_metatile_detection:
        size: 4144
        hash: -7657621180573147007

layers:
    plan: {}
    plan_color: {}
    ortho:
        extension: jpeg
        mime_type: image/jpeg
        empty_tile_detection:
            size: 1096
            hash: -2225832598072171888
        empty_metatile_detection:
            size: 4144
            hash: -7657621180573147007
    mapnik:
        type: mapnik
        mapfile: style.mapnik
        generator_options:
            output_format: png
    grid:
        type: mapnik
        mapfile: style.mapnik
        output_format: grid
        extension: json
        mime_type: application/utfgrid
        resolution: 4
        meta: off
        output_format: grid
        data_buffer: 128
        layers_fields:
            -foo: [name]
            -bar: [name, description]

generation:
    default_cache: local
    default_layers: [plan, plan_color, ortho]
    authorised_user: www-data

    number_process: 8
    maxconsecutiveerrors: 10
    geodata_folder: /var/sig/package

    disable_sync: no
    disable_code: no
    disable_database: no
    disable_fillqueue: no
    disable_tilesgen: no
