language: python

python:
  - 2.6
  - 2.7

before_install:
  - python --version

install:
  - python bootstrap.py --version 1.5.2 --distribute --download-base
            http://pypi.camptocamp.net/distribute-0.6.22_fix-issue-227/ --setup-source
            http://pypi.camptocamp.net/distribute-0.6.22_fix-issue-227/distribute_setup.py
  - ./buildout/bin/buildout

script:
  - find tilecloud_chain -name \*.py | grep -v tilecloud_chain/openlayers.py | xargs ./buildout/bin/flake8 --max-line-length=120

notifications:
  email:
    recipients:
      - stephane.brunner@gmail.com
